package env

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strings"
)

// VarStatus represents the validation state of a single env variable.
type VarStatus int

const (
	VarPresent  VarStatus = iota // key exists in .env with a non-empty value
	VarMissing                   // key in .env.example but missing from .env
	VarEmpty                     // key exists in .env but value is empty
	VarOptional                  // key has no value in .env.example (optional)
	VarExtra                     // key in .env but not in .env.example
)

// VarResult holds the result for one environment variable.
type VarResult struct {
	Key    string
	Status VarStatus
	Value  string // masked or empty
}

// ValidationResult holds the complete validation outcome.
type ValidationResult struct {
	Vars    []VarResult
	Missing []string // keys that are required but absent
	Empty   []string // keys present but empty
	Extra   []string // keys in .env but not in .env.example
}

// IsOK returns true if there are no missing or empty required variables.
func (r *ValidationResult) IsOK() bool {
	return len(r.Missing) == 0 && len(r.Empty) == 0
}

// Validate compares envFile (.env) against exampleFile (.env.example).
// Returns a ValidationResult describing each variable's status.
func Validate(envFile, exampleFile string) (*ValidationResult, error) {
	example, err := parseEnvFile(exampleFile)
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", exampleFile, err)
	}

	actual, err := parseEnvFile(envFile)
	if err != nil && !os.IsNotExist(err) {
		return nil, fmt.Errorf("reading %s: %w", envFile, err)
	}

	result := &ValidationResult{}

	// Check all keys from .env.example
	for _, key := range sortedKeys(example) {
		exampleVal := example[key]
		actualVal, exists := actual[key]

		var status VarStatus
		switch {
		case !exists:
			status = VarMissing
			result.Missing = append(result.Missing, key)
		case actualVal == "":
			if exampleVal == "" {
				status = VarOptional
			} else {
				status = VarEmpty
				result.Empty = append(result.Empty, key)
			}
		default:
			status = VarPresent
		}

		result.Vars = append(result.Vars, VarResult{
			Key:    key,
			Status: status,
			Value:  maskValue(key, actualVal),
		})
	}

	// Find extra keys (in .env but not .env.example)
	for key := range actual {
		if _, inExample := example[key]; !inExample {
			result.Extra = append(result.Extra, key)
		}
	}
	sort.Strings(result.Extra)

	return result, nil
}

// Sync adds any keys missing from envFile that exist in exampleFile,
// with empty placeholder values. Existing keys are never modified.
func Sync(envFile, exampleFile string) (added []string, err error) {
	example, err := parseEnvFile(exampleFile)
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", exampleFile, err)
	}

	actual, _ := parseEnvFile(envFile) // ignore error — file may not exist yet
	if actual == nil {
		actual = map[string]string{}
	}

	// Open .env in append mode to add only missing keys.
	f, err := os.OpenFile(envFile, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o600)
	if err != nil {
		return nil, fmt.Errorf("opening %s: %w", envFile, err)
	}
	defer f.Close()

	for _, key := range sortedKeys(example) {
		if _, exists := actual[key]; !exists {
			line := fmt.Sprintf("\n%s=\n", key)
			if _, err := fmt.Fprint(f, line); err != nil {
				return added, fmt.Errorf("writing to %s: %w", envFile, err)
			}
			added = append(added, key)
		}
	}

	return added, nil
}

// GenerateExample creates/overwrites exampleFile using keys from envFile
// but with all values stripped (replaced with empty or placeholder).
func GenerateExample(envFile, exampleFile string) error {
	lines, err := readLines(envFile)
	if err != nil {
		return fmt.Errorf("reading %s: %w", envFile, err)
	}

	var out strings.Builder
	out.WriteString("# Generated by go-tk env generate-example\n# Do not commit real values — this file is safe to commit.\n\n")

	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			out.WriteString(line + "\n")
			continue
		}
		if idx := strings.Index(line, "="); idx >= 0 {
			key := line[:idx]
			out.WriteString(key + "=\n")
		}
	}

	return os.WriteFile(exampleFile, []byte(out.String()), 0o644)
}

// parseEnvFile reads an env file into a key→value map.
// Comments (#) and blank lines are ignored. Values may be quoted.
func parseEnvFile(path string) (map[string]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	result := make(map[string]string)
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		idx := strings.Index(line, "=")
		if idx < 0 {
			continue
		}
		key := strings.TrimSpace(line[:idx])
		val := strings.TrimSpace(line[idx+1:])
		// Strip surrounding quotes.
		if len(val) >= 2 && ((val[0] == '"' && val[len(val)-1] == '"') || (val[0] == '\'' && val[len(val)-1] == '\'')) {
			val = val[1 : len(val)-1]
		}
		result[key] = val
	}
	return result, scanner.Err()
}

// readLines returns raw lines from a file.
func readLines(path string) ([]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var lines []string
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		lines = append(lines, scanner.Text())
	}
	return lines, scanner.Err()
}

// maskValue masks sensitive values for display.
func maskValue(key, val string) string {
	if val == "" {
		return ""
	}
	lower := strings.ToLower(key)
	for _, sensitive := range []string{"secret", "password", "token", "key", "dsn", "url"} {
		if strings.Contains(lower, sensitive) {
			if len(val) > 4 {
				return val[:2] + strings.Repeat("*", len(val)-4) + val[len(val)-2:]
			}
			return "****"
		}
	}
	return val
}

// sortedKeys returns map keys in sorted order.
func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
